module.exports = {
    MENU: "MENU",

    // FALLAS
    FALLA_PEDIR_CI: "FALLA_PEDIR_CI",
    FALLA_MENU: "FALLA_MENU",
    FALLA_LUZ_ROJA: "FALLA_LUZ_ROJA",
    FALLA_LUZ_PON: "FALLA_LUZ_PON",
    FALLA_WIFI: "FALLA_WIFI",
    FALLA_SOLUCION: "FALLA_SOLUCION",
    FALLA_DETALLE: "FALLA_DETALLE",

    // INSTALACIONES
    INST_NOMBRE: "INST_NOMBRE",
    INST_CELULAR: "INST_CELULAR",
    INST_DIRECCION: "INST_DIRECCION",

    // CONSULTAS
    CONSULTA_INSTALACION: "CONSULTA_INSTALACION",
    CONSULTA_REPORTE: "CONSULTA_REPORTE"
};
